"""add post title slug excerpt

Revision ID: 57b12c5fcaad
Revises: de502e00277b
Create Date: 2026-04-12 20:25:07.984027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b12c5fcaad'
down_revision = 'de502e00277b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=220), nullable=True))
        batch_op.add_column(sa.Column('excerpt', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('read_time', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_slug'))
        batch_op.drop_column('read_time')
        batch_op.drop_column('excerpt')
        batch_op.drop_column('slug')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
